apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-todo-app 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ajay-devops-cloud/To-doMicrofrontend
    path: manifest
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
